version: '3'
services:
  dev:
    build:       
      context: .
      dockerfile: Dockerfile      
    image: docker/dev
    # Keeps container running
    command: tail -f /dev/null
    ports:
      #- "8081:22"
      - "5001:5001"
    volumes:
    - /home/arni/Projects/Kaggle/the-winton-stock-market-challenge_github:/mnt/the-winton-stock-market-challenge_github
    - /home/arni/Projects/temp:/mnt/temp